def build_wheel(wheel_directory, config_settings=None, metadata_directory=None): ...


def build_sdist(sdist_directory, config_settings=None): ...


def get_requires_for_build_wheel(config_settings=None): ...


def get_requires_for_build_sdist(config_settings=None): ...


def prepare_metadata_for_build_wheel(metadata_directory, config_settings=None): ...
